apiVersion: v1
kind: Service
metadata:
  name: virtdbnx-db
spec:
  ports:
  - name: "1410"
    port: 1410
    targetPort: 1433
  selector:
    app: virtdbnx-db
  type: LoadBalancer
  loadBalancerIP: 10.64.35.208  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: virtdbnx-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: virtdbnx-db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: My_P@ssw0rd!
        image: gcr.io/active-module-235013/github.com/diannemg/aspdemoprem:virtdbnx_db
        name: virtdbnx-db
        ports:
        - containerPort: 1433
        volumeMounts:
        - mountPath: /var/opt/mssql/sqldata/udb
          name: virtdbnx-asp
      restartPolicy: Always
      volumes:
      - name: virtdbnx-asp
        persistentVolumeClaim:
          claimName: virtdbnx-db-pvc
