apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: My_P@ssw0rd!
        image: tmeregistry.azurecr.io/virtdbnx-asp-db
        name: db
        ports:
        - containerPort: 1433
        resources: {}
        volumeMounts:
        - mountPath: /var/opt/mssql/sqldata/udb
          name: virtdbnx-asp
      restartPolicy: Always
      volumes:
      - name: virtdbnx-asp
        persistentVolumeClaim:
          claimName: virtdbnx-asp
status: {}
