apiVersion: v1
kind: Service
metadata:
  name: virtdbnx-db-ext
  labels:
    app: virtdbnx-db
spec:
  ports:
  - name: "mssql"
    protocol: TCP
    port: 1410
    targetPort: 1433
  selector:
      app: virtdbnx-db
  type: LoadBalancer
  loadBalancerIP: 10.64.35.208
---
