apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: virtdbnx
  name: virtdbnx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: virtdbnx
    spec:
      containers:
      - image: tmeregistry.azurecr.io/virtdbnx-asp
        name: virtdbnx
        ports:
        - containerPort: 80
        - containerPort: 2222
        resources: {}
      restartPolicy: Always
status: {}
