apiVersion: v1
kind: Service
metadata:
  name: virtdbnx-asp     
spec:
  ports:
  - name: "50938"
    port: 50938
    targetPort: 80
  - name: "2222"
    port: 2222                                                                                  
    targetPort: 2222
  selector:
    app: virtdbnx-asp
type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: virtdbnx-asp
spec:
  replicas: 2
  selector:
    matchLabels:
       app: virtdbnx-asp
  template:
    metadata:
      labels:
        app: virtdbnx-asp
    spec:
      containers:
      - image: tmeregistry.azurecr.io/virtdbnx-asp
        name: virtdbnx
        ports:
        - containerPort: 80
        - containerPort: 2222
      restartPolicy: Always
