apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtdbnx-recover-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: hpecv-recover-class
