FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY virtdbnx/virtdbnx.csproj virtdbnx/
RUN dotnet restore virtdbnx/virtdbnx.csproj
COPY . .
WORKDIR /src/virtdbnx
RUN dotnet build virtdbnx.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish virtdbnx.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "virtdbnx.dll"]